language = "zh"

[[projects]]
name = "ecom"

[projects.agent]
type = "claudecode"

[projects.agent.options]
work_dir = "D:/wechat_claude"
mode = "auto"
reasoning_effort = "low"
allowed_tools = ["Read", "Grep", "Glob", "Bash", "Edit", "Write", "WebSearch", "WebFetch"]

[instant_reply]
enabled = true
content = "🤔 思考中..."

[[projects.platforms]]
type = "weixin"

[projects.platforms.options]
token = "faef8feb5b83@im.bot:0600002cb3853bf7af1826515b6eb56ee82d44"
base_url = "https://ilinkai.weixin.qq.com"
account_id = "faef8feb5b83@im.bot"
